### PR TITLE
Don't return error if string is null (starts with 0)

### PR DESCRIPTION
**Pull request by flesnuk**

### CODE REVIEW

**Comment by thehowl** [comment]
Hi there! Thanks for the contribution. Could you point me at an instance where this actually happens? IIRC this never occurred while working on bancho servers - I'm assuming you're using the package to read osu!.db or others?

**Comment by flesnuk** [comment]
yeah, with scores.db replays, which have always a null string for the Life bar graph, since it doesn't store it.

Look at the end of this page: https://osu.ppy.sh/help/wiki/osu!_File_Formats/Db_(file_format) , the null String would be the Life bar graph in a .osr (it shares the same structure)

**Comment by flesnuk** [comment]
Also, a string can start with 0x00 anyways, you shouldn't consider that an error ( https://osu.ppy.sh/help/wiki/osu!_File_Formats/Osr_(file_format) [Data types part] )

**Comment by thehowl** [comment]
Yep, it looks like it's as you say. Technically I guess there should be a more proper check (make sure byte is either `\x11` or `\x00`, return an error otherwise), but that probably doesn't really matter since if it isn't one of those, then the db file is corrupted in some other way.

**Pull request merged**
